server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: default-authorizationserver/keystore.p12
    key-store-password: changeit
    key-alias: demo

http:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: ""
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: "/h2-console"
  security:
    user:
      name: user1
      password: password
      roles: user, admin
    oauth2:
      authorizationserver:
        client:
          messaging-client:
            registration:
              client-id: "messaging-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc"
                - "http://127.0.0.1:8080/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "message.read"
                - "message.write"
            require-authorization-consent: true
            token:
              access-token-time-to-live: 90s
          messaging-client-opaque:
            registration:
              client-id: "messaging-client-opaque"
              client-secret: "{noop}secret2"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logged-out"
              scopes:
                - "message.read"
                - "message.write"
            require-authorization-consent: true
            token:
              access-token-format: reference
